let a =3;
let b=5;
let c=b-a;
let d=b*a;
let e=b/a;
let f=b%a;
document.write("Difference of "+a+" and "+b+" is "+c+"<br>");
document.write("Multiplication of "+a+" and "+b+" is "+d+"<br>");
document.write("Division of "+a+" and "+b+" is "+e+"<br>");
document.write("Modulus of "+a+" and "+b+" is "+f+"<br>");